---
title: "rnaVeloDygen ver2"
output: html_notebook
---

```{r}
rm(list = ls())
gc()
```

```{r}
library(tidyverse)
library(rlang)
library(dyngen)
# library(dyngen.manuscript)
```

## function in dyngen.manuscript
In case, dyngen.manuscript cannot be installed
```{r}
`%cache%` <- function(file, value) {
  if (!file.exists(file)) {
    write_rds(value, file, compress = "gz")
    value
  } else {
    read_rds(file)
  }
}

make_directory_function <- function(prefix, postfix = character(0)) {
  function(...) {
    file <- do.call(file.path, as.list(c(prefix, paste0(...), postfix)))
    folder <- gsub("[^/]*$", "", file)
    if (!file.exists(folder)) {
      dir.create(folder, recursive = TRUE)
    }
    file
  }
}

start_analysis <- function(experiment_id) {
  list(
    temporary = make_directory_function(paste0("temporary_files/", experiment_id)),
    result = make_directory_function(paste0("result_files/", experiment_id)),
    dataset_folder = make_directory_function(paste0("temporary_files/", experiment_id, "/datasets"), postfix = ""),
    model_file = make_directory_function(paste0("temporary_files/", experiment_id, "/datasets"), postfix = "model.rds"),
    dataset_file = make_directory_function(paste0("temporary_files/", experiment_id, "/datasets"), postfix = "dataset.rds"),
    velocity_file = function(dataset_id, method_id, params_id) {
      make_directory_function(
        prefix = paste0("temporary_files/", experiment_id, "/velocity"),
        postfix = "velocity.rds"
      )(
        paste0(dataset_id, "-", method_id, "-", params_id)
      )
    }
  )
}
```


```{r}
# helper function for location of file storing, give the location, then store it in the location
# include exp$temporary, exp$result, exp$dataset_folder, exp$model_file, exp$dataset_file, exp$velocity_file
# interface, function("path")
exp <- start_analysis("usecase_rna_velocity_b2b")
names(list_backbones())
```


```{r}
# store the configuration file in the current working directory, file_name % cache% data
# design_datasets, dataframe store the configuration
design_datasets <- exp$result("design_datasets.rds") %cache% {
  crossing(

    # linear_simple
    backbone_name = names(list_backbones())[[13]],
    seed = c(6),
    #tr_rate_multiplier = c(1),
    #spl_rate_multiplier = c(1),
    #degrade_multiplier = c(1),
    #num_cells = c(200)
    tr_rate_multiplier = c(1, 5, 10),
    spl_rate_multiplier = c(0.1, 0.5, 1, 5, 10),
    degrade_multiplier = c(1),
    num_cells = c(210, 220, 230, 240, 250, 260, 270, 280, 290, 300),
  ) %>%
    mutate(id = paste0(backbone_name, "_", seed, "_", tr_rate_multiplier , "_", spl_rate_multiplier, "_", num_cells))
}
design_datasets
```

## run simulator
```{r}
pwalk(design_datasets, function(id, seed, backbone_name, tr_rate_multiplier, spl_rate_multiplier, degrade_multiplier, num_cells) {
  if (!file.exists(exp$dataset_file(id))) {

    cat("## Generating ", id, "\n", sep = "")
    s <- seed
    set.seed(s)
    # backbone name
    backbone <- dyngen::list_backbones()[[backbone_name]]()
    # num_cell params
    num_cells <- num_cells
    # num tfs, here is 24 for bifurcating
    num_tfs <- nrow(backbone$module_info) * 2
    # num targets 
    num_targets <- 70 * 2
    # num hks
    num_hks <- 0 
    # distance matric
    distance_matric <- "eucildean"
    # tf_network params
    tf_network_params <- tf_network_default()
    # feature network params
    feature_network_params <- feature_network_default()
    # kinetic params
    kinetic_params <- kinetics_default()
    
    kinetic_params$sampler_tfs <- function(...) {
      x <- kinetics_default()$sampler_tfs(...)
      # the proportion
      x$transcription_rate <- x$transcription_rate * tr_rate_multiplier
      x$splicing_rate <- x$splicing_rate * spl_rate_multiplier
      x$mrna_halflife <- x$mrna_halflife * degrade_multiplier
      x
    }
    
    # gold standard params
    gold_standard_params <- gold_standard_default()
    # simulation_params
    simulation_params <- simulation_default(
      census_interval = 1,
      experiment_params = bind_rows(simulation_type_wild_type(num_simulations = 5),
                                    # not sure about knockdown
                                    simulation_type_knockdown(num_simulations = 0)),
      # reaction_firing is an approximation of true reaction propensity
      store_reaction_firings = TRUE,
      store_reaction_propensities = TRUE,
      compute_propensity_ratios = TRUE,
      kinetics_noise_function = kinetics_noise_simple(mean = 1, sd = 0.005),
      # noiseless version, kinetics_noise_function = kinetics_noise_none()
    )
    # experiment params, capture rate... default value 
    experiment_params <- experiment_snapshot()
    # or 
    # experiment_params <- experiment_synchronised()

    # step 1
    model <-
      initialise_model(
        id = id,
        backbone = backbone,
        num_cells = num_cells,
        num_tfs = num_tfs,
        num_targets = num_targets,
        num_hks = num_hks,

        kinetics_params = kinetic_params,
        simulation_params = simulation_params,
        
        # same as default
        # gold_standard_params = gold_standard_params,
        # tf_network_params = tf_network_params,
        # feature_network_params = feature_network_params,
        # experiment_params = experiment_params,
        num_cores = 7,
        download_cache_dir = "~/.cache/dyngen",
        verbose = TRUE
      )
    
    # step 2 
    #generate_dataset(
      #model,
      # store the result out directly, exp$dataset_folder(id) returns a character of direction
      #output_dir = exp$dataset_folder(id),
      #make_plots = TRUE
    #)
    
    model <- model %>% generate_tf_network() %>% generate_feature_network() %>%
         generate_kinetics() %>% generate_gold_standard() %>%
         generate_cells() %>% generate_experiment()

    write_rds(model,paste0("./velo_benchmark/models/",id,"_models.rds"))
    
    # equals to 
    # model <- model %>% generate_tf_network() %>% generate_feature_network() %>% 
    #     generate_kinetics() %>% generate_gold_standard() %>% 
    #     generate_cells() %>% generate_experiment()
    
    # write_rds(model,paste0("./velo_benchmark/models/",id,"_models.rds"))
    gc()
  }
})

```

## store result
```{r}
pwalk(
  design_datasets, function(id, seed, backbone_name, tr_rate_multiplier, spl_rate_multiplier, degrade_multiplier, num_cells){
    
    #read_rds(paste0("./velo_benchmark/models/",id,"_models.rds"))
    
    model <- read_rds(paste0("./velo_benchmark/models/",id,"_models.rds"))
    # dataset is the model with log transform count
    #dataset <- read_rds(exp$dataset_file(id))
    dataset <- wrap_dataset(model, store_dimred = FALSE, 
        store_cellwise_grn = FALSE, store_propensity_ratios = FALSE)
    
    #realcounts <- model$experiment_params$realcount
    
    
    # for this version no velocity data
    # velocity <- read_rds(exp$velocity_file(id))
    # velocity <- model$simulations$rna_velocity
    
    # log transform, from dataset
    spliced_log <- as.matrix(dataset$expression)
    unspliced_log <- as.matrix(dataset$expression_unspliced)
    protein_log <- as.matrix(dataset$expression_protein)
    cell_info <- dataset$cell_info
    propensity_ratio <- dataset$propensity_ratio
    
    # count from model before log tranform
    spliced <- as.matrix(model$experiment$counts_mrna)
    unspliced <- as.matrix(model$experiment$counts_premrna)
    protein <- as.matrix(model$experiment$counts_protein)
    
    # raw count, before library construction and no dropout effect
    step_ixs <- cell_info$step_ix
    true_counts <- model$simulations$counts[step_ixs, , drop = FALSE]
    unspliced_t <- as.matrix(true_counts[, model$feature_info$mol_premrna, drop = FALSE])
    spliced_t <- as.matrix(true_counts[, model$feature_info$mol_mrna, drop = FALSE])
    protein_t <- as.matrix(true_counts[, model$feature_info$mol_protein, drop = FALSE])
    
    # print(model$simulations$propensity_ratios)
    # propensity <- model$simulations$reaction_propensities
    # print(model$simulations$reaction_firings)
    # print(names(model$simulations))
    # problem with propensities too, propensities has NULL
    # print(model$simulations$reaction_propensities)
    print(nrow(unspliced_t))
    print(nrow(unspliced))
    
    
    write.csv(spliced,file = paste0("./data/",id,"_spliced.csv"))
    write.csv(unspliced,file = paste0("./data/",id,"_unspliced.csv"))
    #write.csv(protein,file = paste0("./data/",id,"_protein.csv"))
    write.csv(cell_info,file = paste0("./data/",id,"_cell_info.csv"))

    #(spliced_t,file = paste0("./result_files/",id,"_spliced_t.csv"))
    #write.csv(unspliced_t,file = paste0("./result_files/",id,"_unspliced_t.csv"))
    #write.csv(protein_t,file = paste0("./result_files/",id,"_unspliced_t.csv"))

  }
  
)
```




